### ISSUE TITLE
user story

### ISSUE THREAD

**Issue by harrymac1972** [Olivia-the-G/next-new-niche#2]
Wonderful job please!

**Comment by Stas-Cell-Max** [comment]
As an Admin, I want to approve or reject blog posts submitted by contributors, so that I can maintain high-quality content on the blog.

As a Contributor, I want to submit my blog posts for review, so that I can share my wine experiences with the community.

As a Subscriber, I want to access premium content, so that I can enjoy exclusive wine insights and reviews.

As a Guest, I want to search for blog posts by region and wine type, so that I can easily find content relevant to my interests.

As a User, I want to comment on blog posts, so that I can engage with the content and community.

**Comment by karina-yuk** [comment]
User Story for Admin and User:
As an Admin, I want to manage blog posts and comments, so that I can ensure the content quality and community engagement.
As a User, I want to explore, read, and interact with blog content, so that I can enjoy and participate in the wine community.

Acceptance Criteria:
User Experience:
WHEN a User access the blog,
THEN they are presented with post about wines.
WHEN a User want to read more about the post and or add comment,
THEN they are presented with the options to either Sign Up or Sign In.
WHEN a User click on Sign Up,
THEN they are presented with a page where they will provide the email, password, and username for the sign up.
WHEN a User click on Sign In,
THEN they are presented with a page where they will input the username, password for the sign in.
WHEN a User is logged in,
THEN they are presented with home page where they can get to see all the post/articles about wine.
WHEN a User navigates to a blog post,
THEN they can view the post content, author, publication date, and comments.
WHEN a User click on Sign Out,
THEN they are logged out and back to hope page with the posts.
